### ISSUE TITLE
Bug: Copy source file preview link stopped working

### ISSUE THREAD

**Issue by sean-kang** [zanllp/sd-webui-infinite-image-browsing#118] opened 2023-05-09 06:53 UTC
Since the latest update that was supposed to fix the missing translation issue, the function stopped working. If I click "Copy source file preview link", it does not show any message at all. I also tried to paste to check if the link was actually copied and the message was missing, it did not paste anything either. It seems completely not functioning at the moment.

**Comment by zanllp** [comment] 2023-05-09 09:29
Can you check if there are any error messages in the console of the browser?

**Comment by zanllp** [comment] 2023-05-09 12:50
I tested it locally, on the cloud, and on Gradio Share without any issues. Perhaps the issue you encountered was caused by running it on HTTP and not on localhost.

**Comment by sean-kang** [comment] 2023-05-10 10:14
Here is the error from FireFox web browser.

```
TypeError: items is undefined
    onContextMenuClick http://localhost:7860/infinite_image_browsing/fe-static/assets/fullScreenContextMenu-b27853eb.js:2
    fr http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    sn http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    fC http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    2 http://localhost:7860/infinite_image_browsing/fe-static/assets/fullScreenContextMenu-b27853eb.js:3
    fr http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    sn http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    sn http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    fC http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:1
    B http://localhost:7860/infinite_image_browsing/fe-static/assets/index-016ca010.js:90

**Comment by zanllp** [comment] 2023-05-10 12:26
It's fixed now. It's still better to use Chrome, as I tested it mostly on Chrome. This issue occurred because Firefox happens to not support this standard.

**Closed** 2023-05-11 04:29 UTC
