### ISSUE TITLE
Support for relative folder paths

### ISSUE THREAD

**Issue by NutchapolSal** [zanllp/sd-webui-infinite-image-browsing#92] opened 2023-05-06 03:00 UTC
Currently when using relative paths for output directory (such as `outputs/txt2img-images`,`outputs/txt2img-grids` etc. which are the default settings), Quick Move actions fail to work (including from "Use Walk mode to browse images" buttons) with "Move failed. Check your path input."

It tries to go to the `outputs` folder immediately instead of navigating to the correct drive and folder, and fails

I think it could be solved by adding the current working directory into the path first (like `D:/foo/bar/stable-diffusion-webui/outputs/txt2img-images`) before doing the Quick Move

**Comment by zanllp** [comment] 2023-05-06 08:51
The feature should be supported currently and works well on my computer. 

Could you please check if there are any errors in the browser console? If there are any errors, please take a screenshot and show it to me.

I have recently encountered some issues where the Python backend returns folder names in lowercase when retrieving the folder list on some computers, which causes this error due to the mismatched folder names. This may be the cause of the issue

**Comment by NutchapolSal** [comment] 2023-05-06 10:37
> Python backend returns folder names in lowercase when retrieving the folder list on some computers

that's definitely the issue, my absolute path is `F:/gits/AUTOMATIC1111/stable-diffusion-webui/outputs`

![image](https://user-images.githubusercontent.com/17706539/236618880-3b63e0ed-0980-4d08-9680-6ec44d6d09d0.png)

**Comment by zanllp** [comment] 2023-05-06 10:45
You can try updating the extension. I have enabled ignoring case sensitivity for path matching. 
I'm not sure why it happened。 on my Win10 PC，it returns the correct folder name .

**Comment by NutchapolSal** [comment] 2023-05-06 10:45
i think a better way to approach this is for the UI to be able to "open a view in a directory" directly instead of only able to "open a view of directory root" then navigate into the folder

**Comment by NutchapolSal** [comment] 2023-05-06 10:53
> You can try updating the extension. I have enabled ignoring case sensitivity for path matching. 

i can confirm that this has fixed the issue for me, but this could cause problems in case-sensitive systems

**Comment by zanllp** [comment] 2023-05-06 10:58
I'm not sure what the structure of your outputs is. But for me, it creates subfolders based on time. And this is useful when running independently, so it's still better to open them layer by layer.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/25872019/236619686-8079de98-a3db-4ba9-b10c-688e495bfc52.png">

**Comment by zanllp** [comment] 2023-05-06 11:01
> > You can try updating the extension. I have enabled ignoring case sensitivity for path matching.
> 
> i can confirm that this has fixed the issue for me, but this could cause problems in case-sensitive systems

I don't think anyone would deliberately create names that are the same but with different cases. 

Maybe I can also add a system check to prevent this

**Comment by zanllp** [comment] 2023-05-06 14:54
I have closed this issue. If you have any further problems or requests, please create a new issue.

**Closed by zanllp** 2023-05-06 14:54 UTC
