### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by cjps-br** [zanllp/sd-webui-infinite-image-browsing#444] opened 2023-10-03 17:34 UTC
When rebuilding the index in the search function, I am receiving the error "sqlite3.IntegrityError: UNIQUE constraint failed:" (below a dump of the error), on line 339 of the datamodel.py module. It seems to me that the error occurs when a record is being inserted into the image_tag table, using the command ""INSERT INTO image_tag (image_id, tag_id) VALUES (?, ?)"" .

I would like to suggest that INSERT INTO be replaced by INSERT OR REPLACE:

INSERT OR REPLACE INTO image_tag (image_id, tag_id) VALUES (?, ?)

DUMP 

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\sd_automatic_1111\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\api.py", line 782, in rebuild_index
    rebuild_image_index(search_dirs=get_img_search_dirs())
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 151, in rebuild_image_index
    update_image_data(search_dirs=search_dirs, is_rebuild=True)
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 131, in update_image_data
    process_folder(dir)
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 62, in process_folder
    process_folder(file_path)
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 62, in process_folder
    process_folder(file_path)
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 102, in process_folder
    safe_save_img_tag(ImageTag(img.id, size_tag.id))
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 51, in safe_save_img_tag
    img_tag.save(conn)  # 原先用来处理一些意外，但是写的正确完全没问题,去掉了try catch
  File "D:\Automatic_data\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\datamodel.py", line 339, in save
    cur.execute(
sqlite3.IntegrityError: UNIQUE constraint failed: image_tag.image_id, image_tag.tag_id

**Comment by zanllp** [comment] 2023-10-06 13:02
In normal circumstances, this issue should not occur. Using "OR REPLACE" simply masks the error without actually resolving the problem. You can try updating to the latest version and repeating the process several times to see if the issue persists. Although I haven't addressed this problem myself, I am currently unable to reproduce it.

**Comment by zanllp** [comment] 2023-11-11 19:12
This issue was resolved at the latest version

**Closed by zanllp** 2023-11-11 19:12 UTC
